### ISSUE TITLE
TypeError: 'generator' object is not subscriptable

### ISSUE THREAD

**Issue by arilwan** [DiogoApostolo/pycol#5]
To reproduce:
```
>>> from pycol_complexity import complexity
>>> complexity = complexity.Complexity('data/pycol-data/61_iris.arff', distance_func="default", file_type="arff")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/venv/lib/python3.10/site-packages/pycol_complexity/complexity.py", line 50, in __init__
    [X,y,meta]=self.__read_file(file_name)
  File "~/venv/lib/python3.10/site-packages/pycol_complexity/complexity.py", line 208, in __read_file
    data = f['data']
TypeError: 'generator' object is not subscriptable
```

Using:
```
$ python -V
Python 3.10.14
```

**Comment by DiogoApostolo** [comment]
Thank you for opening this issue and I apologize for the late replay

I wasn't able to reproduce the issue on my end, I ran the code you posted, but it ran with no errors. Have you figured out anything else? I'm interested in understanding what could be causing this.
